version: 0.1
phases:
  install:
    commands:
      - npm install
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket lorealsourcecodebucket --output-template-file NewSamTemplate.yaml
artifacts:
  type: zip
  files:
    - NewSamTemplate.yaml
